"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-21 18:58:22.714706
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('rejected_count', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=True),
    sa.Column('dataset_version', sa.String(length=128), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'checksum', name='uq_data_sources_snapshot')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('artifact_path', sa.String(length=256), nullable=False),
    sa.Column('dataset_version', sa.String(length=128), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('split', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('dataset_version', sa.String(length=128), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version'], ['models.version'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id')
    )
    op.create_table('neo_objects',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('designation', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('is_potentially_hazardous', sa.Boolean(), nullable=True),
    sa.Column('absolute_magnitude_h', sa.Float(), nullable=True),
    sa.Column('diameter_km', sa.Float(), nullable=True),
    sa.Column('albedo', sa.Float(), nullable=True),
    sa.Column('eccentricity', sa.Float(), nullable=False),
    sa.Column('semi_major_axis_au', sa.Float(), nullable=False),
    sa.Column('perihelion_distance_au', sa.Float(), nullable=False),
    sa.Column('aphelion_distance_au', sa.Float(), nullable=False),
    sa.Column('inclination_deg', sa.Float(), nullable=False),
    sa.Column('ascending_node_deg', sa.Float(), nullable=False),
    sa.Column('argument_of_perihelion_deg', sa.Float(), nullable=False),
    sa.Column('mean_anomaly_deg', sa.Float(), nullable=False),
    sa.Column('mean_motion_deg_per_day', sa.Float(), nullable=False),
    sa.Column('orbital_period_days', sa.Float(), nullable=False),
    sa.Column('earth_moid_au', sa.Float(), nullable=True),
    sa.Column('epoch_jd', sa.Float(), nullable=False),
    sa.Column('condition_code', sa.String(length=4), nullable=True),
    sa.Column('first_obs_date', sa.String(length=16), nullable=False),
    sa.Column('last_obs_date', sa.String(length=16), nullable=False),
    sa.Column('first_obs_year', sa.Integer(), nullable=False),
    sa.Column('n_obs_used', sa.Integer(), nullable=False),
    sa.Column('data_arc_days', sa.Integer(), nullable=True),
    sa.Column('rms', sa.Float(), nullable=False),
    sa.Column('orbit_class', sa.String(length=8), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('designation')
    )
    op.create_table('close_approaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neo_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.String(length=16), nullable=False),
    sa.Column('orbit_id', sa.String(length=16), nullable=True),
    sa.Column('approach_jd', sa.Float(), nullable=False),
    sa.Column('approach_time_tdb', sa.DateTime(), nullable=False),
    sa.Column('distance_au', sa.Float(), nullable=False),
    sa.Column('distance_min_au', sa.Float(), nullable=False),
    sa.Column('distance_max_au', sa.Float(), nullable=False),
    sa.Column('v_rel_km_s', sa.Float(), nullable=False),
    sa.Column('v_inf_km_s', sa.Float(), nullable=True),
    sa.Column('time_uncertainty', sa.String(length=16), nullable=True),
    sa.Column('absolute_magnitude_h', sa.Float(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['neo_id'], ['neo_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neo_id', 'body', 'approach_jd', name='uq_close_approach')
    )
    op.create_index('ix_close_approaches_time', 'close_approaches', ['approach_time_tdb'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neo_id', sa.BigInteger(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version'], ['models.version'], ),
    sa.ForeignKeyConstraint(['neo_id'], ['neo_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_neo_id'), 'predictions', ['neo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_neo_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_close_approaches_time', table_name='close_approaches')
    op.drop_table('close_approaches')
    op.drop_table('neo_objects')
    op.drop_table('experiments')
    op.drop_table('models')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
